apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-secret
data:
  db_username: bXl1c2Vy      # base64 encoded value of 'myuser'
  db_password: ZGF0YWJhc2V  # base64 encoded value of 'database_password'
